//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public animale()
        {
            this.animales_enfermos = new HashSet<animales_enfermos>();
            this.reproduccions = new HashSet<reproduccion>();
        }
    
        public int ID_Animal { get; set; }
        public int Num_Caravana { get; set; }
        public string Especie { get; set; }
        public string Raza { get; set; }
        public string Genero { get; set; }
        public System.DateTime Fecha_Nac { get; set; }
        public float Peso_Nac { get; set; }
        public float IMC_Actual { get; set; }
        public string Observaciones { get; set; }
        public int Cod_Signia { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Fecha_Muerte { get; set; }
        public string Imagen__Ruta_ { get; set; }
        public byte[] Imagen__Foto_ { get; set; }
        public float Peso_Actual { get; set; }
        public Nullable<System.DateTime> Celo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<animales_enfermos> animales_enfermos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reproduccion> reproduccions { get; set; }
    }
}
