//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animales_enfermos
    {
        public int ID_enfermo { get; set; }
        public int ID_animal { get; set; }
        public int ID_enfermedad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual enfermedade enfermedade { get; set; }
        public virtual animale animale { get; set; }
    }
}
