//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfermedade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enfermedade()
        {
            this.animales_enfermos = new HashSet<animales_enfermos>();
        }
    
        public int ID_enfermedad { get; set; }
        public string Nom_Enfermedad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<animales_enfermos> animales_enfermos { get; set; }
    }
}
