//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ganadoEntities : DbContext
    {
        public ganadoEntities()
            : base("name=ganadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rancho> ranchos { get; set; }
        public virtual DbSet<reproduccion> reproduccions { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<animales_enfermos> animales_enfermos { get; set; }
        public virtual DbSet<enfermedade> enfermedades { get; set; }
        public virtual DbSet<animale> animales { get; set; }
    }
}
