//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rancho
    {
        public int ID_Rancho { get; set; }
        public string Nombre_Rancho { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public int Hectareas { get; set; }
        public string Dueño { get; set; }
    }
}
