//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reproduccion
    {
        public int ID_Reprod { get; set; }
        public int ID_Animal { get; set; }
        public int ID_Padre { get; set; }
        public int Embarazos { get; set; }
        public int Partos { get; set; }
        public Nullable<int> Abortos { get; set; }
        public Nullable<int> Partos_Complicaciones { get; set; }
    
        public virtual animale animale { get; set; }
    }
}
