//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooPlot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido_s_ { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Fecha_Nac { get; set; }
    }
}
